### ISSUE TITLE
Extend NATS connection exception message with NATS connection properties

### ISSUE THREAD

**Issue by CarloWakefield** [nats-io/stan.java#135]
Hi!

When the connection to the NATS Server can't be established, this exception is thrown:
```
Caused by: java.io.IOException: Unable to connect to NATS server.
	at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:221)
	at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29)
	at io.nats.client.Nats.createConnection(Nats.java:224)
	at io.nats.client.Nats.connect(Nats.java:153)
	at io.nats.streaming.StreamingConnectionImpl.createNatsConnection(StreamingConnectionImpl.java:316)
	at io.nats.streaming.StreamingConnectionImpl.connect(StreamingConnectionImpl.java:145)
	at io.nats.streaming.StreamingConnectionFactory.createConnection(StreamingConnectionFactory.java:78)
	at com.bearingpoint.platform.etaservice.infrastructure.messaging.nats.NatsDriverStateRequestPublisher.postConstruct(NatsDriverStateRequestPublisher.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 54 common frames omitted
```
It would be very useful if the exception message would be extended with the connection properties. For example: 

> Unable to connect to NATS server with URL nats://some-server:3745 and cluster ID some-cluster-id.

This would come in very handy when reading logs and tracing errors.

Greetings
Carlo

**Comment by sasbury** [comment]
I added more to the exception in the core library, and also added a trace connection option. Closing this for now. Let me know if you need more.
